### PR TITLE
Add typedefs for PVector class

### PR DESCRIPTION
**Pull request by ryanolee**
# What
This adds typescript definitions to the module

# Why
So that when using this library with typescript it can be properly used

### CODE REVIEW

**Comment by ryanolee** [comment]
Let me know if you have any thoughts on this @MAKIO135 👀. Thanks!

**Comment by MAKIO135** [comment]
WOW @ryanolee, thank you!! Pushing PVector to 2022 👏👏👏
I'm not a Typescript user at all, but as long as it does not change the JS code, I believe I can trust you on this part.

**Comment by ryanolee** [comment]
Ahh thanks for taking a look! I have been using it in another typescript
project and copying that file directly into my node_modules/pvectorjs
folder seems to result in things working properly. Most of it was based off
the extensive documentation you already have 😆 ( though there were a few
incorrect function signatures in the documentation I fixed in the TS
definitions so should hopefully cover everything!)

**Comment by MAKIO135** [comment]
Thank you @ryanolee

**Pull request merged**
